gluwa/creditcoin3

Cargo.lock
node/Cargo.toml
node/src/benchmarking.rs
node/src/chain_spec.rs
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

Switch to split Substrate/EVM addresses

---

.github/workflows/ci.yml
.gitignore
cli/tsconfig.json

CSUB-788: Add CI jobs for static checking of JavaScript sources

---

.github/workflows/wasm.yml
cli/src/lib/common.ts
cli/src/scripts/runtimeUpgrade.ts

- Builds on top of #52. 
- Needs a functioning CI in order to execute and see that it works

CSUB-860: Automatically upgrade WASM runtime on Devnet

---

.github/workflows/ci.yml
cli/src/index.ts

CSUB-787: Add a sanity test job for creditcoin3 cli binary

---

.github/workflows/ci.yml
Dockerfile

CSUB-787: Add cc3-cli to docker image

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/wasm.yml
rust-toolchain.toml

This is a cherry-pick from #51. Doesn't resolve the issue in #51 but I though we may just as well upgrade the version of this tool.
---

CI: Use paritytech/srtool v1.73.0 & stable rustc 1.73.0

---

README.md

in a few more places which we had forgotten
---

Update README to use the appropriate creditcoin3 name

---

.github/workflows/ci.yml
.github/workflows/wasm.yml
Dockerfile

CSUB-787: Upgrade to Node.js 20

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/rpc/mod.rs
node/src/service.rs
runtime/src/version.rs

Mostly for the `grandpa_roundState` RPC which is useful for debugging finality issues
---

Add GRANDPA RPCs

---

Cargo.lock
pallets/bridge/Cargo.toml
pallets/bridge/src/types.rs

Use dependencies from workspace, some of which also happen to be a later version.
---

CSUB-883: Improvements to pallets/bridge/Cargo.toml

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/wasm.yml
pallets/bridge/src/lib.rs

General improvements to CI extracted from #106 for easier reviewing.
---

CSUB-883: General improvements to CI extracted from #106

---

.github/workflows/llvm-cov.yml

CSUB-875: Upload llvm coverage data to Azure and post a comment on a PR

---

.github/workflows/ci.yml

CSUB-972: Add tests for creditcoin3 cli inside the container

---

.github/check-for-used-forks.sh
Cargo.lock
Cargo.toml

CSUB-962, CSUB-963, CSUB-959, CSUB-969, CSUB-974: Polkadot Release v1.1.0 patch

---

cli/src/test/blockchain-tests/pallet_bridge/approve-collection.test.ts

CSUB-913: Adjust integration test for refactored parseAmount() function

---

.gitleaksignore

Fixes breaking Megalinter CI job affecting several PRs.
---

Fix: Add .gitleaksignore line for Sudo address

---

.github/workflows/wasm.yml

b/c Devnet has been updated with pallet_scheduler we can now schedule runtime upgrades in the future instead of applying them immediately!
---

CSUB-899: Reapply "updated wasm workflow to use the scheduler pallet"

---

.github/workflows/release.yml
README.md

CSUB-1008: Updates around unsupported Windows platform

---

cli/src/cli.ts
cli/src/commands/convertAddress.ts
cli/src/commands/options.ts
cli/src/test/integration-tests/convertAddress.test.ts

[CSUB-957] Add convert-address command to CLI

---

.github/workflows/release.yml

CSUB-1020: Adjust release pipeline's upload-artifact/download-artifact for v4

---

cli/src/commands/evm/fund.ts

CSUB-1011: Remove a console.log() call used for debugging in `evm fund` command

---

.github/workflows/ci.yml

Execute gasTest tool from @gluwa/evm-network-test

---

.github/check-for-missing-package-json-in-Dependabot-config.sh
.github/dependabot.yml
.github/workflows/ci.yml
chainspecs/devnetSpec.json
chainspecs/testnetSpec.json

- Check `Cargo.toml` files because of https://github.com/gluwa/creditcoin3/pull/169#discussion_r1452283533
- Also check all `package.json` files
- Delete entry for `pallets/bridge/`

CSUB-1011: Check for missing Cargo.toml files in dependabot config

---

cli/src/commands/options.ts
cli/src/lib/parsing.ts
cli/src/test/unit-tests/parsing.test.ts

CSUB-1022: Improvements & tests around parsing integer numbers

---

cli/src/cli.ts

CSUB-1012:  Document a warning in source code

---

cli/src/commands/proxy/actions.ts

CSUB-1021: Improvements on original PR

---

.github/workflows/ci.yml
testing/evm-network-test.sh

will be used later for runtime-upgrade tests

CSUB-861: Refactor smart-contract testing into a reusable script

---

cli/.eslintrc.js
cli/src/test/integration-tests/proxy.test.ts

builds on top of #226 and reorganizes the existing test scenarios into logical groups, minimizes duplication
---

CSUB-1023: Improvements around proxy.test.ts

---

cli/src/commands/proxy/actions.ts
cli/src/test/integration-tests/proxy.test.ts

CSUB-1023: Add negative tests for proxy commands

---

cli/src/test/integration-tests/send.test.ts

CSUB-1025: Reorganize send.test.ts in preparation for adding a proxy test matrix

---

cli/src/commands/staking/setKeys.ts

CSUB-1015: Exit with result.status from set-keys command

---

cli/src/commands/options.ts
cli/src/commands/proxy/actions.ts
cli/src/commands/proxy/commands.ts

CSUB-1045 [CLI] Remove "--delay" command from the CLI

---

cli/src/commands/staking/bond.ts
cli/src/test/integration-tests/proxy.test.ts

CSUB-1015: Exit with transaction status from bond command

---

cli/src/test/integration-tests/convertAddress.test.ts
cli/src/test/integration-tests/wizard.test.ts

cherry-picked from #232. 
These can be merged independently.

CSUB-1025: House-keeping of some integration tests

---

cli/src/commands/staking/chill.ts
cli/src/commands/staking/validate.ts

CSUB-1015: Exit with transaction status from validate & chill commands

---

cli/src/commands/staking/wizard.ts
cli/src/lib/proxy/index.ts
cli/src/test/integration-tests/wizard.test.ts

Do not merge yet! Need to take a deeper look into balance checks for proxy accounts (to ensure they can pay for fees).
This PR adds:
- Check if Proxy account is valid for specified validator address in Wizard
- Check if signer account can pay for fees & bond amount
- Fix issue where when using a proxy bond step was never skipped
---

[CSUB-1042] Improve CLI Wizard error handling

---

.github/workflows/ci.yml
cli/src/test/integration-tests/bond.test.ts
cli/src/test/integration-tests/chill.test.ts
cli/src/test/integration-tests/convertAddress.test.ts
cli/src/test/integration-tests/distribute-rewards.test.ts
cli/src/test/integration-tests/evm.test.ts
cli/src/test/integration-tests/helpers.ts
cli/src/test/integration-tests/proxy.test.ts
cli/src/test/integration-tests/send.test.ts
cli/src/test/integration-tests/set-keys.test.ts
cli/src/test/integration-tests/showAddress.test.ts
cli/src/test/integration-tests/unbond.test.ts
cli/src/test/integration-tests/validate.test.ts
cli/src/test/integration-tests/validatorCycle.test.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts
cli/src/test/integration-tests/wizard.test.ts

CSUB-1025: Add testing matrix for cli commands and proxies

---

cli/src/test/integration-tests/status.test.ts

CSUB-1033: Add integration test for the `status` command

---

cli/src/commands/balance.ts

[CSUB-1061] Fix EVM balance was not added to Balance command total

---

.github/workflows/ci.yml
Dockerfile
cli/README.md
cli/package.json
cli/src/commands/evm/index.ts
cli/tsconfig.json
cli/yarn.lock

[CSUB-1060] Rename creditcoin3 CLI to just creditcoin

---

cli/src/test/integration-tests/balance.test.ts
cli/src/test/integration-tests/helpers.ts

CSUB-1032: Add integration test for the `balance` command

---

cli/src/test/integration-tests/convertAddress.test.ts
cli/src/test/integration-tests/evm.test.ts
cli/src/test/integration-tests/proxy.test.ts
cli/src/test/integration-tests/showAddress.test.ts

CSUB-1024:  Test cli commands with non-default --url

---

.github/workflows/release.yml

One of the sanity checks failed here
https://github.com/gluwa/creditcoin3/actions/runs/8236512427/job/22523091397 so need to figure out what's wrong with it.
---

CSUB-1073: Don't compare branch origin for tags (temporary workaround)

---

.github/workflows/ci.yml

CSUB-1086: Add evm-tracing feature when executing `cargo test`

---

.github/check-bootnodes.sh
.github/workflows/ci.yml
chainspecs/devnetSpecRaw.json
chainspecs/testnetSpecRaw.json

Removed hardcoded local bootnodes from chainspecs
---

chore: remove bootnodes from chainspecs

---

.github/workflows/ci.yml

extracted from #282 with some improvements.

CSUB-1006: Don't commit creditcoin.json if it is the only file that changed

---

Cargo.lock
Cargo.toml
node/src/rpc/eth.rs
node/src/rpc/mod.rs
runtime/src/lib.rs
runtime/src/version.rs

a few improvements revealed to us when using a newer rustc while waiting for the issues in #159 to be resolved.
---

CSUB-1071: Improvements revealed by newer rustc

---

cli/src/lib/staking/validatorStatus.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts

which unfortunately does not reproduce CSUB-1090 so there must be other conditions that influence the state here.
---

CSUB-1090: Add integration test for withdrawing partially unbonded funds

---

SECURITY.md

Update security policy with link to CC3 bug bounty program

---

.github/workflows/ci.yml
cli/package.json
cli/src/lib/api.ts
cli/src/test/integration-tests.config.ts
cli/src/test/integrationTestSetupAfterEnv.ts
cli/src/test/utils.ts
cli/tsconfig.json

splitting https://github.com/gluwa/creditcoin3/pull/290 into multiple parts in order to find out which commit causes the failure seen when executing proxy=no in https://github.com/gluwa/creditcoin3/pull/290.

CSUB-1099: Launch isolated creditcoin3-node processes before individual test groups

---

.github/workflows/ci.yml

see announcement at the top of
https://github.com/actions/runner-images/blob/ubuntu22/20240401.4/images/ubuntu/Ubuntu2204-Readme.md
---

CSUB-1114: Replace `docker-compose` with `docker compose`

---

cli/package.json
cli/src/lib/staking/validatorStatus.ts
cli/yarn.lock

Does not change how the actual value is calculated, just how it is returned to the user! 
---

CSUB-1103: General improvements around unbonding time calculation

---

.github/workflows/ci.yml
cli/src/test/integration-tests/validatorCycle.test.ts

CSUB-1100: Conditionally skip validatorCycle test scenario

---

cli/src/test/integration-tests/bond.test.ts
cli/src/test/integration-tests/chill.test.ts
cli/src/test/integration-tests/distribute-rewards.test.ts
cli/src/test/integration-tests/set-keys.test.ts
cli/src/test/integration-tests/unbond.test.ts
cli/src/test/integration-tests/validate.test.ts
cli/src/test/integration-tests/validatorCycle.test.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts
cli/src/test/integration-tests/wizard.test.ts

Note: 2 commits b/c the last one of them was cherry-picked from #318.
---

CSUB-1100: Reduce the amount of sleep() waiting for block sync

---

cli/src/test/integration-tests/withdraw-unbonded.test.ts

CSUB-1100: Optimize withdraw unbonded test

---

.gitleaksignore
cli/src/lib/staking/validatorStatus.ts

- Builds on top of #316 in order to display more information in the `status` command while performing local experiments; needs a rebase.
- I will cherry-pick #307 on top of this PR and submit it separately to see if it will all work, then move the commit here if it does.

CSUB-1103: Fix unboding time calculation

---

cli/package.json
cli/src/test/integration-tests.config.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts
cli/yarn.lock

New tests for #322 ! Obsoletes #307!
---

CSUB-1103: Assert on unbonding time rebased onto PR #322

---

cli/src/test/blockchain-tests/evm-tracing.test.ts

because this is still part of the "setup" portion of this test
---

Slight refactor for evm-tracing blockchain test

---

cli/src/commands/options.ts
cli/src/commands/send.ts
cli/src/commands/staking/bond.ts
cli/src/commands/staking/chill.ts
cli/src/commands/staking/distribute.ts
cli/src/commands/staking/setKeys.ts
cli/src/commands/staking/unbond.ts
cli/src/commands/staking/validate.ts
cli/src/commands/staking/withdraw.ts
cli/src/commands/staking/wizard.ts
cli/src/lib/account/keyring.ts
cli/src/test/integration-tests/helpers.ts

because this is more explicit
WARNING: documentation needs to be updated once a new container version is published
---

CSUB-1029: Rename --use-proxy to --proxy-for for all cli commands

---

.github/workflows/wasm.yml
cli/src/scripts/runtimeUpgrade.ts

CSUB-1071: More patches for subwasm & devnet update

---

cli/src/test/blockchain-tests/substrate-transfer.test.ts
precompiles/substrate-transfer/src/tests.rs

Follow up to #327. Only the last 9 commits are relevant. 
---

CSUB-1135: Add more tests and test cleanup

---

cli/src/commands/proxy/actions.ts
cli/src/commands/showAddress.ts
cli/src/commands/staking/bond.ts
cli/src/commands/staking/wizard.ts
cli/src/lib/account/keyring.ts
cli/src/lib/staking/bond.ts
cli/src/lib/tx.ts
cli/src/test/integration-tests/bond.test.ts
cli/src/test/integration-tests/chill.test.ts
cli/src/test/integration-tests/distribute-rewards.test.ts
cli/src/test/integration-tests/evm.test.ts
cli/src/test/integration-tests/helpers.ts
cli/src/test/integration-tests/send.test.ts
cli/src/test/integration-tests/set-keys.test.ts
cli/src/test/integration-tests/unbond.test.ts
cli/src/test/integration-tests/validate.test.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts
cli/src/test/integration-tests/wizard.test.ts

CSUB-1030: Refactor internal functions and fix bug when checking if caller/proxy can pay transaction fees

---

.github/query-gha

CSUB-1130: Add script to query workflow execution times from GitHub

---

cli/src/cli.ts
cli/src/commands/options.ts
cli/src/lib/account/keyring.ts

CSUB-1028: Remove duplicate option

---

.github/provision-github-runner.sh
.github/runner.bicep

A few improvements, extracted from #352, which are independent of which environment we chose for hosting the self-hosted VMs.
---

CSUB-1131: General improvements for self hosted runners

---

Cargo.lock
Cargo.toml
cli/src/test/blockchain-tests/substrate-transfer.test.ts
cli/src/test/blockchainSetup.ts
runtime/src/version.rs

Mandatory version bump, keeping all branches in sync.  
cherry-picked from #365 
---

CSUB-1158: Bump version to 3.27.0

---

.github/linode-cloud-init.template
.github/workflows/ci.yml
.github/workflows/runtime-upgrade.yml
cli/src/test/integration-tests.config.ts
cli/src/test/integrationTestSetupAfterEnv.ts

NOTE: some of the commits for Azure should be removed/squashed directly with the ones for Linode
---

CSUB-1132: Use self-hosted runners in Linode

---

.github/workflows/ci.yml
docs/smart-contract-development/with-hardhat/hardhat.config.ts

CSUB-1088: Deploy contracts to local Hardhat instance

---

docs/smart-contract-development/with-hardhat/hardhat-creditcoin3.config.ts

b/c we've got CI steps which already successfully deploy to Devnet without this import. For example:
https://github.com/gluwa/creditcoin3/actions/runs/9369193529/job/25796327016?pr=380
---

CSUB-1088: Add a missing import which doesn't seem to be needed

---

Cargo.lock
Cargo.toml
runtime/src/version.rs

chore: bump to 3.28

---

.github/dependabot.yml
docs/smart-contract-development/with-ethers.js/index.html
docs/smart-contract-development/with-ethers.js/package-lock.json
docs/smart-contract-development/with-ethers.js/package.json
docs/smart-contract-development/with-ethers.js/script.js

CSUB-1088: Ethers.js example

---

.github/workflows/ci.yml
.github/workflows/llvm-cov.yml
.github/workflows/release.yml
.github/workflows/runtime-upgrade.yml
.github/workflows/wasm.yml

CSUB-1174: Use a forked action with updated Node.js version

---

.github/check-solidity-source-vs-metadata.sh
.github/workflows/ci.yml
.gitignore
Cargo.lock
Cargo.toml
precompiles/metadata/abi-creator.sh
runtime/src/version.rs

CSUB-1169: Add sanity test for precompiles

---

.github/workflows/release.yml

Continue creating a GitHub release if Windows build fails

---

cli/src/commands/staking/wizard.ts

CSUB-1143: Update user message for wizard command

---

.github/workflows/llvm-cov.yml

CSUB-1193: Rework llvm-cov workflow

---

.github/workflows/ci.yml
Dockerfile

Add chainspecs to docker image

---

.github/workflows/runtime-upgrade.yml

RPC URLs don't need to change
---

Update boot node for Mainnet

---

.github/workflows/release.yml

b/c MacOS 11 is no longer available. See:
https://github.com/gluwa/creditcoin/pull/1687
---

Use MacOS-13 runners for release

---

.github/provision-github-runner.sh
.github/workflows/runtime-upgrade.yml

Specify a missing ENV variable that was changed recently. Self-hosted provisioning passing at:
https://github.com/gluwa/creditcoin3/actions/runs/10593029616/job/29362625897?pr=450

CSUB-1260: Fix runtime upgrade tests failures

---

node/src/chain_spec.rs
node/src/command.rs

CSUB-1259 add mainnet shorthand

---

.github/dependabot.yml

see https://github.com/gluwa/creditcoin3/actions/runs/10850908844/job/30113422026
Introduced in https://github.com/gluwa/creditcoin3/pull/469

CSUB-1273: Fix-up dependabot.yml config

---

.github/check-extrinsics.sh
.github/workflows/ci.yml

CSUB-1219: Enable metadata comparisons with Testnet & Mainnet

---

.github/workflows/mega-linter.yml

although in reality it acts as a redirect
---

Update URL to appease MegaLinter

---

.github/check-bootnodes.sh
.github/workflows/ci.yml
chainspecs/dryRunSpec.json
chainspecs/dryRunSpecRaw.json
node/src/chain_spec.rs
node/src/command.rs

More checks for chainspec files

---

.github/workflows/runtime-upgrade.yml
cli/src/scripts/runtimeUpgrade.ts
cli/src/test/blockchain-tests/substrate-transfer.test.ts

CSUB-1415: Adjust sudo balance before testing against fork

---

.github/workflows/mega-linter.yml

see upstream issue description at
https://github.com/oxsecurity/megalinter/issues/4617

Pin MegaLinter version to workaround CSUB-1418

---

.github/workflows/check-chain-snapshots.yml
actionlint.yml

CSUB-1417: Add CI jobs which check latest chain snapshots

---

.github/workflows/check-chain-snapshots.yml

Took 17 mins to sync 1 day's worth of blocks:
https://github.com/gluwa/creditcoin3/actions/runs/13236707961/job/36943111083?pr=567

CSUB-1417: Bump timeout

---

.github/workflows/check-chain-snapshots.yml

CSUB-1417: Adjust where results are sent

---

.github/workflows/check-chain-snapshots.yml
actionlint.yml

Reformat YAML files

---

.github/workflows/runtime-upgrade.yml

Fixes https://github.com/gluwa/creditcoin3/pull/590#pullrequestreview-2793402909. 
Should merge here and also port into cc3-next once PR #590 is merged.

Patch for the runtime-upgrade workflow

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

Substrate fees

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

CSUB-1728: rename millicents to microctc for consistency

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
runtime/src/version.rs

Csub 1733: fix srtool build

---

.github/workflows/create-devnet-release.yml
.github/workflows/release.yml

CSUB-1734: Updates to the auto -devnet release pipeline

---

.github/workflows/ci.yml
.github/workflows/rebase-branch-and-propose-pr.yml

CSUB-1715: More fixes for git-rebase sanity checks after unification
