node/src/chain_spec.rs

Currently when spinning up a local dev chain, the Sudo account (Alice) starts with all funds locked by staking and it cannot even pay for Sudo transaction fees. This PR lowers initial staking in fresh local devnets from 1M (100%)  to 100k (10%).
It does not change the public devnet specs.
---

Local Dev: Avoid staking all of Alice funds

---

Cargo.lock
Cargo.toml
node/src/benchmarking.rs
runtime/src/lib.rs
runtime/src/version.rs

This is what we had on CC2, and it's strictly more flexible than the status quo.
This also fixes the rebased staking dashboard without requiring changes on that side, since that code assumes that the address type is `MultiAddress`. There isn't really any downside to this change, as far as I'm aware.
---

CSUB-905: Use `MultiAddress` as the runtime's address type

---

.github/workflows/ci.yml

Should avoid errors like this one:
https://github.com/gluwa/creditcoin3/actions/runs/7167855981/job/19515123149?pr=81

CSUB-862: Auto-commit typedefs updates only if submitter has sufficient priviledges

---

node/src/chain_spec.rs

It's a leftover from the frontier template and it causes weirdness since it causes the total issuance to be inaccurate
---

Remove accounts with `u128::MAX` balance from genesis

---

Cargo.lock
node/Cargo.toml
node/src/rpc/eth.rs
node/src/rpc/eth/consensus_data_provider.rs
node/src/service.rs

This fixes the issue where RPC nodes ban other peers and become isolated on the network. Pablo had a hunch that it was related to ethereum/EVM interactions, and it turns out that was the case!
Some of the ethereum RPCs which take a block number/hash as a parameter also permit you to specify `"pending"`. For instance the second parameter on `eth_getBalance`:
```json
{"jsonrpc": "2.0", "method": "eth_getBalance", "params": ["0x77777FeDdddFfC19Ff86DB637967013e6C6A116C", "pending"],"id": 1}
```
The expected behavior is to run the RPC against the next, pending block (which has not been created yet!) but has pending transactions included in its state.
How this works in frontier is to basically create a new block that "looks" like a legitimate block, and then create a runtime API to execute …

[CSUB-989] Fix babe consensus data provider (for pending eth RPCs)

---

cli/package.json
cli/yarn.lock

Fixed by bumping the polkadot/api version: https://github.com/polkadot-js/api/releases/tag/v10.11.2
---

[CSUB 984] Fix CLI "lookup index" warning

---

.github/workflows/ci.yml
Dockerfile

rename the container entrypoint to creditcoin3-node!
---

Use consistent names for binary inside/outside of container

---

.github/workflows/wasm.yml

This reverts commit 1d71f9174af772751b4fb8ec30b54def74402205.
Note: we need to schedule the update with delay 0, so that the scheduler pallet makes it into Devnet. See failure in https://github.com/gluwa/creditcoin3/actions/runs/7557406838/job/20577164306
Once Devnet had been updated to v3.14 or later we can restore the original commit and exercise the scheduler functionality.
---

CSUB-899: Revert "updated wasm workflow to use the scheduler pallet"

---

cli/src/commands/evm/fund.ts
cli/src/commands/options.ts
cli/src/commands/staking/distribute.ts

[CSUB-1013] Fix typo & create eraOption

---

.github/workflows/release.yml

Upgrading to `upload-artifact@v4` and `download-artifact@v4` broke the release pipeline, as it included breaking changes: ([failed run](https://github.com/gluwa/creditcoin3/actions/runs/7465483455/job/20318088171)). This reverts back to v3 to fix it
---

CSUB-1020: Fix release pipeline

---

.github/workflows/ci.yml
cli/src/test/blockchainSetup.ts

so that we can keep configuration for multiple environments in a single place.  
Will be used as part of runtime-upgrade testing and possibly other tests which need EVM private keys.

CSUB-861, CSUB-1011: Make it possible to override environment for smart contract testing

---

cli/src/test/blockchain-tests/evm-tracing.test.ts
cli/src/test/blockchainSetup.ts

b/c none of our production nodes are executed with this functionality. This is only used by Subscan.
During runtime upgrade testing and/or testing against Testnet/Devnet/Mainnet these EVM tracing tests will not be executed.

CSUB-1011: Make EVM tracing testing conditional

---

cli/src/test/blockchain-tests/evm-tracing.test.ts
cli/src/test/blockchainSetup.ts

there is no loan-flow in CC3 so lender & borrower don't make sense anymore. Rename them to `alice` and `bob` so we can still use them inside of tests!

CSUB-861: Rename arguments in createSigner() function

---

cli/src/commands/proxy/actions.ts
cli/src/lib/proxy/index.ts

From the ticket:
Code to change : 
1. Limit a validator account to 1 type of proxy (All OR staking OR non-transfer)
3. Limit a proxy account to one validator only (disable multiple validators assigned to a single proxy)
All of the changes are limited to the `setProxyAction` in `src/commands/proxy/action.ts` and `src/lib/proxy`
TODO: Rebase after CSUB-102 is merged

CSUB-1021: CC3 Clarify proxy combinations

---

cli/src/commands/staking/bond.ts
cli/src/commands/staking/chill.ts
cli/src/commands/staking/unbond.ts
cli/src/commands/staking/withdraw.ts
cli/src/commands/staking/wizard.ts
cli/src/lib/account/keyring.ts
cli/src/lib/tx.ts

in the terminology of the proxy pallet the original account is called a delegate, so trying to match this terminology.
Also there is a function called `validateAddress` which is used for input validation and the names are rather similar and IMO that's a bit confusing.

CSUB-1012: Rename validatorAddress() to delegateAddress()

---

cli/src/test/integration-tests/proxy.test.ts

NOTES:
- Bob's node is on port :9955 while the default is :9944!
- Some calls use the default URL and connect to Alice's node to provide some variability making sure both default and non-default URLs will work

CSUB-1023: Point the --url option to a non-default location when testing proxies

---

.github/check-tag-suffix-vs-origin-branch.sh
.github/workflows/release.yml

to avoid the situation where a release is tagged as x.y.z-testnet but the release artifacts are actually built from the `dev` branch!
If I execute from the topic branch:
```
.github/check-tag-suffix-vs-origin-branch.sh 
INFO: git tag: '3.18.0-devnet'
INFO: suffix from git tag: 'devnet'
INFO: nearest git branch 'testing/stricter-control-over-tag-suffixes'
FAIL: Looks like tag name doesn't match the branch it came from
```
When I execute the same script from the `testnet` branch
```
INFO: git tag: '3.15.3-testnet-22-g2481f3f'
INFO: suffix from git tag: 'testnet'
INFO: nearest git branch 'testnet'
PASS: good match for -testnet releases
```
When I execute the same script from the `dev` branch:
```
INFO: git tag: '3.18.0-devnet'
INFO: suffix from git tag: 'devnet'
INFO: nearest git branch …
```

Stricter control over git tag name suffixes

---

.github/check-tag-suffix-vs-origin-branch.sh
.github/workflows/release.yml

During the sanity check step which tries to find out which branch a git tag came from the source code is checked out by GitHub in a detached state and the previous implementation was returning "(HEAD" which  failed in https://github.com/gluwa/creditcoin3/actions/runs/8236512427/job/22523091397. 
Instead of matching the currently checkout out branch (grep for `* `) find the name of a remote branch containing the same tag ref and then compare that against the expected list of origin branches (dev, testnet or main). 
For experimentation I made a tag called `3.21.xx01-testnet` on the origin branch of this PR and it triggered the pipeline execution in https://github.com/gluwa/creditcoin3/actions/runs/8237469339/job/22526275349. Here we can see:
- the local git checkout in a detached state:
``` …
```

CSUB-1073: Improve sanity checks for git tags origin during release

---

.github/CODEOWNERS

Change the codeowners team b/c PRs automatically ask for review from David Lebeen and David Wahid who aren't actively working in this repository. For example see #278

Update CODEOWNERS to Blockchain-Engineering

---

cli/src/test/integrationTestSetupAfterEnv.ts
cli/src/test/utils.ts

splitting #290 into multiple parts in order to find out which commit causes the failure seen when executing `proxy=no` in #290.

CSUB-1099: Short-circuit test execution if the chain has stopped finalizing

---

cli/src/commands/staking/chill.ts
cli/src/commands/status.ts

it looks like that getValidatorStatus() is always being called correctly with the address of an expected validator regardless of whether or not we are using proxy accounts.
This change just makes all of the invocations consistent with one another in case we'd like to somehow assert/grep on these calls in the future!
---

CSUB-1026: Rename internal variables for future compatibility

---

cli/src/test/integration-tests/helpers.ts
cli/src/test/integration-tests/validatorCycle.test.ts
cli/src/test/integration-tests/withdraw-unbonded.test.ts

when calling waitEras() during the integration tests we shouldn't be forcing new eras by default because this is not what the standard chain behvior is.
For the situation where we know what we're doing and really want to force a new era there is the function `forceNewEra()` which the scenario should be calling directly!
---

CSUB-1103: Do not force new eras during tests

---

.lycheeignore
cli/src/commands/status.ts
cli/src/lib/chain/status.ts
cli/src/lib/staking/validatorStatus.ts
cli/src/test/integration-tests/status.test.ts
cli/src/test/utils.ts

will display new information in header which can be useful for debugging:
```
$ node dist/cli.js status --substrate-address 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp
Validator 5EEoJZYPpTYGX1t3shaQbqhRmqvdvoaTycY1gJ4TB8spDgPp:
┌───────────────────────┬─────────────────────────────┐
│ Current Era: 21       │ Block: 592; Finalized: 590  │
├───────────────────────┼─────────────────────────────┤
│ Bonded                │ Yes                         │
├───────────────────────┼─────────────────────────────┤
│ Validating            │ No                          │
├───────────────────────┼─────────────────────────────┤
│ Waiting               │ No                          │
├───────────────────────┼─────────────────────────────┤
│ Active                │ No                          │ …
```

CSUB-1090: Display current era and block info in status command

---

.github/workflows/runtime-upgrade.yml
.github/workflows/wasm.yml

currently we've pinned the version to 0.17.1 which fails to build with rustc 1.77.0:
https://github.com/gluwa/creditcoin3/actions/runs/8832658427/job/24251068397
---

CSUB-1071: dry-run install subwasm and then update it

---

.github/provision-github-runner.sh

because in some environments hostname isn't configured automatically and defaults to `localhost`, which causes GitHub runner provisioning to fail when you have more than one runner.
---

CSUB-1132: Configure runner name explicitly, do not rely on hostname

---

.github/check-version.sh

Require a mandatory version bump when we change anything in `precompiles/`, similar to `runtime/`. 
Detecting a change -> https://github.com/gluwa/creditcoin3/actions/runs/9403560833/job/25900388284?pr=387
(#387 this is a copy of #385 + the current commit).
---

Testing: When precompiles/ changes ask for mandatory version bump!

---

.gitleaksignore
testing/package-lock.json
testing/package.json

CSUB-1144: Update smart contract test tool to 0.1.5

---

.github/workflows/release.yml

these are conditionally executed on macos (cross arch builds) and I've missed them the first time around.
---

CSUB-1180: Add continue-on-error flags for 2 more steps in release pipeline

---

.github/provision-github-runner.sh
.github/provision-linode-vm.sh
.github/remove-linode-vm.sh
.github/workflows/ci.yml

CSUB-1234: More prep work around self-hosted runners

---

.github/provision-github-runner.sh
.github/workflows/ci.yml

this prevents hard-coding the value and allows us to easily migrate commits between the 2 repositories.

CSUB-1234: Specify GitHub repository for self-hosted provisioning from the CI job

---

.gitleaksignore

Gitleaks thinks that a sudo public key in a chainspec is a leak. Had to add an exemption for the sudo key used in mainnet launch dry run 3
Also removed outdated exemptions corresponding to commits that were squashed.

Made proper exception to gitleaks, fixing megalint

---

.github/workflows/check-runtime-changes.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/llvm-cov.yml
.github/workflows/mega-linter.yml
.github/workflows/release.yml
.github/workflows/runtime-upgrade.yml
.github/workflows/wasm.yml

trying to make it use LFS everywhere where we use action checkout

---

.github/check-for-missing-Cargo-toml-in-Dependabot-config.sh
.github/check-for-missing-package-json-in-Dependabot-config.sh
.github/dependabot.yml

in order to reduce the number of open pull requests. See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
Needed to update how sanity check scripts work as well.

CSUB-1273: Group Dependabot version updates together

---

.github/dependabot.yml

As soon as PR #464 was metged it triggered Dependabot to scan for new updates which opened
https://github.com/gluwa/creditcoin3/pull/465 and https://github.com/gluwa/creditcoin3/pull/466.
We can do better and group github-actions and docker updates too.

CSUB-1273: Enable PR groupping for github-actions & docker updates too

---

.github/workflows/ci.yml
.github/workflows/runtime-upgrade.yml

Include the repository name as part of the self-hosted runner VM hostname, to make it easier to connect VM -> repository -> workflow:
Old names at top of image, new names below:
NOTE: the reported MegaLinter failure is unrelated, see https://github.com/gluwa/creditcoin3/pull/483#discussion_r1796700865
NOTE: provisioning & running on Azure using the new naming scheme appears to be working as well, see:
https://github.com/gluwa/creditcoin3/actions/runs/11290155122/job/31401798798?pr=509
---

CSUB-1322: Include repository name as part of self-hosted runner hostname

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

update runtime's polynomial fn to adjust formula of  WeightToFeeCoef to make tx fees on cc3 the same as it is on cc2.
with a new updated formula the fees on cc3 and cc2 are:
```
transfers tx: 9.8mili vs 11.35mili
staking payout_stakers: 10.27mili vs 11.38mili
```
---

fix: update runtime's polynomial fn to adjust formula of WeightToFeeCoef

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

* update tx payment pallet LengthToFee TransactionByteFee
* fix clippy
* cargo toml to v 39
---

Prepare testnet 3.39

---

.github/workflows/mega-linter.yml

CSUB-1374: Tell gitleaks to scan only commits in the current PR

---

.github/workflows/ci.yml
.github/workflows/llvm-cov.yml
.github/workflows/release.yml
.github/workflows/runtime-upgrade.yml
.github/workflows/wasm.yml
Dockerfile

From its changelog:
https://github.com/rust-lang/rustup/blob/master/CHANGELOG.md#1280---2025-03-04
> rustup will no longer automatically install the active toolchain if it is not installed. pr#3985
> To ensure its installation, run rustup toolchain install with no arguments.
---

Force rustup to install missing toolchain b/c it broke all of our builds

---

.github/workflows/check-chain-snapshots.yml
.github/workflows/runtime-upgrade.yml

b/c devops will be making new snapshots every 3 days so there's no need to execute this consistently every day

Execute chain-snapshots testing only on Monday & Thursday

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs
runtime/src/version.rs

This reverts commit 05fa652f6fb3bb116ef8c5190c46136568b23824.
---

Reverts default base fee back 

---

.github/workflows/ci.yml
.github/workflows/runtime-upgrade.yml

a previous effort to fix some issues and bump the version was attempted in https://github.com/gluwa/creditcoin3/pull/556 however the original issue wasn't solved.
Disabling these tests because they are always failing with false positives!
---

Disable @gluwa/evm-network-test execution until SMC-1036 is resolved

---

.github/workflows/release.yml

because they are unnecessary
- Windows is unsupported anyway, see https://github.com/gluwa/creditcoin/security/advisories/GHSA-cx5c-xwcv-vhmq
- There is no official statement for MacOS native, however Cairo doesn't work on anything but Linux x86_64 and MacOS users will not be able to transition from Creditcoin3 to Creditcoin Next. So dropping the builds b/c sooner or later we will have to do so.
This change also simplifies the release workflow and makes it easier to unify with the build workflows exercised on pull requests as a follow-up step.

CSUB-1734: Drop MacOS and Windows release builds

---

.github/bump-version.sh
Cargo.lock
Cargo.toml
runtime/src/version.rs

- revert the broken Cargo.lock file
- change how Cargo.lock file gets updated after a version change in order to not update additional 3rd party dependencies
---

CSUB-1734: Revert broken Cargo.lock file and fix how we update version to avoid upgrading 3rd party dependencies

---

.github/workflows/build-docker.yml
.github/workflows/ci.yml

Otherwise the docker-test job will pull the image from the Internet and not exercise the image which was built from the pull request!
---

CSUB-1734: Share locally built docker image between CI jobs
